version: '3'
services:
  # mysql
  db:
    image: mysql:5.7
    container_name: application_chat_app_mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"

  # elastic search
  elasticsearch:
    image: elasticsearch:7.5.0
    container_name: es01
    volumes:
      - .:/app
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
  
  # redis
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    container_name: chat_app_redis_cache
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

  # cron jobs
  cron_job:
    build: .
    command: cron -f
    depends_on:
      - db
      - elasticsearch
      - redis

  # rails app
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - .:/myapp
    environment:
      - ELASTICSEARCH_URL=elasticsearch
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
      - redis

volumes:
  my-db:
  redis_data:
    driver: local